# Generated by Django 6.0.3 on 2026-05-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsetting',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_settings', to='gameapi.room'),
        ),
    ]
