from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('check-auth/', views.check_auth, name='check_auth'),
    path('score/', views.score, name='score'),
    path('rooms/', views.rooms_list_create, name='rooms_list_create'),
    path('rooms/<int:pk>/', views.room_detail, name='room_detail'),
    path('scores/', views.scores_list_create, name='scores_list_create'),
    path('scores/<int:pk>/', views.score_detail, name='score_detail'),
    path('blockly-results/', views.blocklyresults_list_create, name='blocklyresults_list_create'),
    path('blockly-results/<int:pk>/', views.blocklyresult_detail, name='blocklyresult_detail'),
    path('submissions/', views.submissions_list_create, name='submissions_list_create'),
    path('submissions/<int:pk>/', views.submission_detail, name='submission_detail'),
    path('progress/', views.progress_list_create, name='progress_list_create'),
    path('progress/<int:pk>/', views.progress_detail, name='progress_detail'),
    path('simulation-runs/', views.simulationruns_list_create, name='simulationruns_list_create'),
    path('simulation-runs/<int:pk>/', views.simulationrun_detail, name='simulationrun_detail'),
    path('device-states/', views.devicestates_list_create, name='devicestates_list_create'),
    path('device-states/<int:pk>/', views.devicestate_detail, name='devicestate_detail'),
    path('attempts/', views.attempts_list_create, name='attempts_list_create'),
    path('attempts/<int:pk>/', views.attempt_detail, name='attempt_detail'),
    path('assets/', views.assets_list_create, name='assets_list_create'),
    path('assets/<int:pk>/', views.asset_detail, name='asset_detail'),
    path('activity-logs/', views.activitylogs_list_create, name='activitylogs_list_create'),
    path('activity-logs/<int:pk>/', views.activitylog_detail, name='activitylog_detail'),
    path('leaderboards/', views.leaderboards_list_create, name='leaderboards_list_create'),
    path('leaderboards/<int:pk>/', views.leaderboard_detail, name='leaderboard_detail'),
    path('settings/', views.settings_list_create, name='settings_list_create'),
    path('settings/<int:pk>/', views.setting_detail, name='setting_detail'),
    path('room-settings/', views.roomsettings_list_create, name='roomsettings_list_create'),
    path('room-settings/<int:pk>/', views.roomsetting_detail, name='roomsetting_detail'),
    path('user-profiles/', views.userprofiles_list_create, name='userprofiles_list_create'),
    path('user-profiles/<int:pk>/', views.userprofile_detail, name='userprofile_detail'),
    path('student-profiles/', views.studentprofiles_list_create, name='studentprofiles_list_create'),
    path('student-profiles/<int:pk>/', views.studentprofile_detail, name='studentprofile_detail'),
    path('teacher-profiles/', views.teacherprofiles_list_create, name='teacherprofiles_list_create'),
    path('teacher-profiles/<int:pk>/', views.teacherprofile_detail, name='teacherprofile_detail'),
]